version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Berlin"

  # The root pom
  - package-ecosystem: "maven"
    directory: "/src/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Berlin"

  # Gomod updates
  - package-ecosystem: "gomod"
    directory: "/src/acceptance/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Berlin"

  # Gomod updates
  - package-ecosystem: "gomod"
    directory: "/src/autoscaler/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Berlin"

  # Gomod updates
  - package-ecosystem: "gomod"
    directory: "/src/changelog/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Berlin"

  # Gomod updates
  - package-ecosystem: "gomod"
    directory: "/src/changeloglockcleaner/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Berlin"
