golang/go1.13.linux-amd64.tar.gz:
  size: 120050424
  sha: sha256:68a2297eb099d1a76097905a2ce334e3155004ec08cdea85f24527be3c48e856
  object_id: bcb0a27b-78fc-4545-4786-8498dd07be62
maven/apache-maven-3.5.4-bin.tar.gz:
  size: 8842660
  object_id: b5e0cf3e-032e-4fdf-64f8-f0519281a3a1
  sha: 22cac91b3557586bb1eba326f2f7727543ff15e3
nodejs/node-v8.11.4-darwin-x64.tar.gz:
  size: 16042407
  object_id: cc5c6ea9-9f1c-4c9d-7fe7-b1c0fd50e72c
  sha: ae434fecf15ad21686cf9bc4ea88a6bb2d6b5906
nodejs/node-v8.11.4-linux-x64.tar.xz:
  size: 11351232
  object_id: 74319675-b9d5-4e07-58f1-b632aa7ba7c1
  sha: 3b1552d91cf853fdca32d163a991f17cc1ffb288
openjdk/openjdk-10.0.1_linux-x64_bin.tar.gz:
  size: 204885801
  object_id: b4e6fb76-a537-4a4d-53d9-e3a84fe613b6
  sha: 1377697996cad66def4f6627d13a031a26af9b7c
openjdk/openjdk-10.0.1_osx-x64_bin.tar.gz:
  size: 200863681
  object_id: a026032a-86ac-4362-4630-2e660b957c55
  sha: 85f722da8da7a151d8500a19d535e7fbf979ba71
