---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ghcr.io/cloudfoundry/app-autoscaler-release-tools
    tag: main

params:

inputs:
- name: ci
- name: bbl-state

run:
  path: ci/ci/cf-infrastructure/scripts/update-dns-servers.sh
