---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ghcr.io/cloudfoundry/app-autoscaler-ci-deploy
    tag: master

inputs:
- name: app-autoscaler-release
- name: app-autoscaler-ci
- name: golang-release
- name: java-release

params:
  GIT_USER_NAME: CI Bot
  GIT_USER_EMAIL: ci@cloudfoundry.org
  UPLOADER_KEY: ((autoscaler_blobstore_uploader_key))
  GITHUB_ACCESS_TOKEN: ((autoscaler_access_token))
  GITHUB_PRIVATE_KEY: ((autoscaler_git_key))
  type:

run:
  path: app-autoscaler-ci/autoscaler/tasks/update-sdk/update_package.sh

