---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ghcr.io/cloudfoundry/app-autoscaler-release-deploy
    tag: master
inputs:
  - name: ops-files
  - name: custom-ops
  - name: ci
outputs:
  - name: combined-ops
run:
  path: ci/ci/autoscaler/scripts/combine-ops.sh
