name: ARC - generate
on:
  pull_request:

concurrency:
  group: "${{ github.workflow }}/${{ github.ref }}"
  cancel-in-progress: true

jobs:
  generate:
    name: ensure fakes are up to date
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Go Build
        run: |
          source .envrc
          pushd src/autoscaler
            make buildtools
            make generate
            git diff
            git status
          popd

      - name: Check if there is any change
        id: get_changes
        run: echo "changed=$(git status --porcelain | wc -l)"  >> $GITHUB_OUTPUT
      - name: Process changes
        if: steps.get_changes.outputs.changed != 0
        run: |
          echo "::error::Fakes are out of date, run make generate to update"
          exit 1
